import { useState, useRef, useLayoutEffect } from 'react'
import BioTemplate from './BioTemplate'

import photoLotus      from '../../Images/AI_Female/sample-lotus.jpg'
import photoArtDeco    from '../../Images/AI_Female/sample-art-deco.jpg'
import photoFloralVine from '../../Images/AI_Female/sample-floral-vine.jpg'
import photoPeacock    from '../../Images/AI_Female/sample-peacock.jpg'
import photoMandala    from '../../Images/AI_Female/sample-mandala.jpg'
import photoCelestial  from '../../Images/AI_Female/sample-celestial.jpg'
import photoBridal     from '../../Images/AI_Female/sample-bridal.jpg'
import photoMinimal    from '../../Images/AI_Female/sample-minimal.jpg'
import photoRoyal      from '../../Images/AI_Female/sample-royal.jpg'
import photoModern     from '../../Images/AI_Female/sample-modern.jpg'
import photoAmethyst   from '../../Images/AI_Female/sample-amethyst.jpg'
import photoEmber      from '../../Images/AI_Female/sample-ember.jpg'
import photoRose       from '../../Images/AI_Female/sample-rose.jpg'
import photoMidnight   from '../../Images/AI_Female/sample-midnight.jpg'

export const SAMPLE_BY_TEMPLATE = {
  // ── FEMALE ──────────────────────────────────────────────────────────────
  lotus: {
    fullName: 'Priya Sharma', dateOfBirth: '1998-03-12', age: '26', gender: 'Female',
    height: "5'4\"", weight: '55 kg', bloodGroup: 'B+',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Iyer', motherTongue: 'Telugu',
    education: 'B.Tech (Computer Science)', college: 'JNTU Hyderabad',
    occupation: 'Software Engineer', company: 'Infosys', income: '8 LPA', workLocation: 'Bengaluru',
    fatherName: 'Ramesh Sharma', fatherOccupation: 'Retired Government Officer',
    motherName: 'Sunita Sharma', motherOccupation: 'Homemaker',
    brothers: '1 Elder Brother (Married)', sisters: 'None',
    familyType: 'Nuclear', familyStatus: 'Middle Class', nativePlace: 'Tirupati, Andhra Pradesh',
    hobbies: 'Classical Dance, Reading, Cooking', about: 'Family-oriented, calm & composed, loves to travel',
    rashi: 'Vrishabha', nakshatra: 'Rohini', gotra: 'Kashyapa', manglik: 'No',
    address: '12, MG Road, Koramangala', city: 'Bengaluru', state: 'Karnataka',
    phone: '+91 90000 00000', email: 'priya.sharma@email.com',
    photo: photoLotus, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'telugu', customFields: [],
  },
  artDeco: {
    fullName: 'Kavya Nair', dateOfBirth: '1997-07-22', age: '27', gender: 'Female',
    height: "5'5\"", weight: '58 kg', bloodGroup: 'O+',
    religion: 'Hindu', caste: 'Nair', subCaste: '', motherTongue: 'Malayalam',
    education: 'MBBS', college: 'Govt. Medical College, Kozhikode',
    occupation: 'Doctor', company: 'Amrita Institute of Medical Sciences', income: '14 LPA', workLocation: 'Kochi',
    fatherName: 'Suresh Nair', fatherOccupation: 'Chartered Accountant',
    motherName: 'Lekha Nair', motherOccupation: 'School Teacher',
    brothers: 'None', sisters: '1 Younger Sister (Student)',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Thrissur, Kerala',
    hobbies: 'Carnatic Music, Swimming, Sketching', about: 'Disciplined and compassionate — values family traditions deeply',
    rashi: 'Karka', nakshatra: 'Pushya', gotra: 'Bharadvaja', manglik: 'No',
    address: '45, Panampilly Nagar', city: 'Kochi', state: 'Kerala',
    phone: '+91 90000 00000', email: 'kavya.nair@email.com',
    photo: photoArtDeco, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'malayalam', customFields: [],
  },
  floralVine: {
    fullName: 'Ananya Chatterjee', dateOfBirth: '1999-01-15', age: '25', gender: 'Female',
    height: "5'3\"", weight: '52 kg', bloodGroup: 'A+',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Kulin', motherTongue: 'Bengali',
    education: 'M.A. (Literature)', college: 'Jadavpur University, Kolkata',
    occupation: 'Content Strategist', company: 'Times Internet', income: '9 LPA', workLocation: 'Kolkata',
    fatherName: 'Debashis Chatterjee', fatherOccupation: 'Professor',
    motherName: 'Mala Chatterjee', motherOccupation: 'Artist',
    brothers: '1 Elder Brother (Married)', sisters: 'None',
    familyType: 'Joint', familyStatus: 'Middle Class', nativePlace: 'Kolkata, West Bengal',
    hobbies: 'Rabindra Sangeet, Painting, Poetry', about: 'Creative soul — deeply rooted in Bengali culture and the arts',
    rashi: 'Mithuna', nakshatra: 'Ardra', gotra: 'Sandilya', manglik: 'No',
    address: '7B, Lake Gardens', city: 'Kolkata', state: 'West Bengal',
    phone: '+91 90000 00000', email: 'ananya.c@email.com',
    photo: photoFloralVine, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'bengali', customFields: [],
  },
  peacock: {
    fullName: 'Zara Khan', dateOfBirth: '1998-05-10', age: '26', gender: 'Female',
    height: "5'5\"", weight: '57 kg', bloodGroup: 'B+',
    religion: 'Muslim', caste: 'Sunni', subCaste: '', motherTongue: 'Urdu',
    education: 'B.Arch', college: 'School of Planning & Architecture, Delhi',
    occupation: 'Architect', company: 'Morphogenesis Design Studio', income: '10 LPA', workLocation: 'New Delhi',
    fatherName: 'Imran Khan', fatherOccupation: 'IAS Officer',
    motherName: 'Nadia Khan', motherOccupation: 'Homemaker',
    brothers: '1 Elder Brother (Lawyer)', sisters: '1 Younger Sister (Student)',
    familyType: 'Nuclear', familyStatus: 'Affluent', nativePlace: 'Lucknow, Uttar Pradesh',
    hobbies: 'Calligraphy, Travel, Classical Poetry', about: 'Artistic and grounded in faith — passionate about sustainable architecture',
    rashi: '', nakshatra: '', gotra: '', manglik: '',
    address: '22, Nizamuddin East', city: 'New Delhi', state: 'Delhi',
    phone: '+91 90000 00000', email: 'zara.khan@email.com',
    photo: photoPeacock, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto',
    customFields: [
      { id: 'z1', section: 'personal', customTitle: '', label: 'Languages Known', value: 'Urdu, Hindi, English, Arabic' },
      { id: 'z2', section: 'personal', customTitle: '', label: 'Religious Practice', value: 'Observant Sunni Muslim, daily Namaz' },
      { id: 'z3', section: 'custom', customTitle: 'Partner Expectations', label: 'Religion', value: 'Muslim (Sunni preferred)' },
      { id: 'z4', section: 'custom', customTitle: 'Partner Expectations', label: 'Profession', value: 'Any respectable profession' },
      { id: 'z5', section: 'custom', customTitle: 'Partner Expectations', label: 'Age Range', value: '28–35 years' },
      { id: 'z6', section: 'custom', customTitle: 'Partner Expectations', label: 'Location', value: 'Delhi / Mumbai / Abroad considered' },
    ],
  },
  celestial: {
    fullName: "Grace D'Souza", dateOfBirth: '1999-03-25', age: '25', gender: 'Female',
    height: "5'4\"", weight: '54 kg', bloodGroup: 'A-',
    religion: 'Christian', caste: 'Catholic', subCaste: '', motherTongue: 'Konkani',
    education: 'B.E. (Electronics)', college: 'NITK Surathkal',
    occupation: 'Product Manager', company: 'Google India', income: '28 LPA', workLocation: 'Bengaluru',
    fatherName: "Anthony D'Souza", fatherOccupation: 'Merchant Navy Officer',
    motherName: "Maria D'Souza", motherOccupation: 'School Principal',
    brothers: '1 Elder Brother (Canada)', sisters: 'None',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Mangaluru, Karnataka',
    hobbies: 'Western Vocals, Badminton, Baking', about: 'Faith-driven and outgoing — loves community service and good food',
    rashi: '', nakshatra: '', gotra: '', manglik: '',
    address: '8, Koramangala 4th Block', city: 'Bengaluru', state: 'Karnataka',
    phone: '+91 90000 00000', email: 'grace.dsouza@email.com',
    photo: photoCelestial, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto',
    customFields: [
      { id: 'g1', section: 'personal', customTitle: '', label: 'Languages Known', value: 'Konkani, Kannada, English, Hindi' },
      { id: 'g2', section: 'personal', customTitle: '', label: 'Parish', value: "St. Francis Xavier Church, Mangaluru" },
      { id: 'g3', section: 'custom', customTitle: 'Partner Expectations', label: 'Religion', value: 'Christian (Catholic preferred)' },
      { id: 'g4', section: 'custom', customTitle: 'Partner Expectations', label: 'Profession', value: 'Any professional background' },
      { id: 'g5', section: 'custom', customTitle: 'Partner Expectations', label: 'Age Range', value: '27–33 years' },
      { id: 'g6', section: 'custom', customTitle: 'Partner Expectations', label: 'Location', value: 'Bengaluru / Mangaluru / Abroad' },
    ],
  },
  bridal: {
    fullName: 'Meera Joshi', dateOfBirth: '1998-09-08', age: '26', gender: 'Female',
    height: "5'3\"", weight: '53 kg', bloodGroup: 'B+',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Deshastha', motherTongue: 'Marathi',
    education: 'B.Com + CA', college: 'Symbiosis College of Arts & Commerce, Pune',
    occupation: 'Chartered Accountant', company: 'Deloitte India', income: '15 LPA', workLocation: 'Pune',
    fatherName: 'Sudhir Joshi', fatherOccupation: 'Retired Bank Manager',
    motherName: 'Vaishali Joshi', motherOccupation: 'Homemaker',
    brothers: '1 Younger Brother (Student)', sisters: 'None',
    familyType: 'Joint', familyStatus: 'Middle Class', nativePlace: 'Nashik, Maharashtra',
    hobbies: 'Bharatnatyam, Marathi Literature, Cooking', about: 'Traditional yet progressive — deeply values family and culture',
    rashi: 'Kanya', nakshatra: 'Hasta', gotra: 'Kaundinya', manglik: 'No',
    address: '23, Aundh', city: 'Pune', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'meera.joshi@email.com',
    photo: photoBridal, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'marathi', customFields: [],
  },
  rose: {
    fullName: 'Devika Pattnaik', dateOfBirth: '1999-02-14', age: '25', gender: 'Female',
    height: "5'3\"", weight: '52 kg', bloodGroup: 'O-',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Utkal', motherTongue: 'Odia',
    education: 'B.Des (Fashion)', college: 'NIFT Bhubaneswar',
    occupation: 'Fashion Designer', company: 'Fabindia', income: '10 LPA', workLocation: 'New Delhi',
    fatherName: 'Surya Narayan Pattnaik', fatherOccupation: 'Advocate',
    motherName: 'Lipsa Pattnaik', motherOccupation: 'School Teacher',
    brothers: '1 Younger Brother (Student)', sisters: 'None',
    familyType: 'Nuclear', familyStatus: 'Middle Class', nativePlace: 'Bhubaneswar, Odisha',
    hobbies: 'Odissi Dance, Pattachitra Art, Reading', about: 'Creative spirit rooted in Odia culture — designs that tell a story',
    rashi: 'Kumbha', nakshatra: 'Shatabhisha', gotra: 'Vasishtha', manglik: 'No',
    address: '34, Defence Colony', city: 'New Delhi', state: 'Delhi',
    phone: '+91 90000 00000', email: 'devika.p@email.com',
    photo: photoRose, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'odia', customFields: [],
  },

  // ── MALE ────────────────────────────────────────────────────────────────
  mandala: {
    fullName: 'Gurpreet Singh', dateOfBirth: '1996-11-03', age: '28', gender: 'Male',
    height: "5'11\"", weight: '76 kg', bloodGroup: 'O+',
    religion: 'Sikh', caste: 'Jatt', subCaste: '', motherTongue: 'Punjabi',
    education: 'MBA (Finance)', college: 'IIM Lucknow',
    occupation: 'Investment Banker', company: 'ICICI Securities', income: '24 LPA', workLocation: 'Mumbai',
    fatherName: 'Daljit Singh', fatherOccupation: 'Businessman',
    motherName: 'Harpreet Kaur', motherOccupation: 'Homemaker',
    brothers: 'None', sisters: '1 Elder Sister (Married)',
    familyType: 'Nuclear', familyStatus: 'Affluent', nativePlace: 'Amritsar, Punjab',
    hobbies: 'Trekking, Finance & Markets, Cricket', about: 'Ambitious and grounded — deeply devoted to Waheguru, family, and excellence',
    rashi: '', nakshatra: '', gotra: '', manglik: '',
    address: '14, Pali Hill', city: 'Mumbai', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'gurpreet.singh@email.com',
    photo: photoMandala, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto',
    customFields: [
      { id: 'm1', section: 'personal', customTitle: '', label: 'Languages Known', value: 'Punjabi, Hindi, English' },
      { id: 'm2', section: 'personal', customTitle: '', label: 'Religious Practice', value: 'Amritdhari Sikh, regular Gurdwara visits' },
      { id: 'm3', section: 'custom', customTitle: 'Partner Expectations', label: 'Religion', value: 'Sikh (Amritdhari preferred)' },
      { id: 'm4', section: 'custom', customTitle: 'Partner Expectations', label: 'Age Range', value: '24–30 years' },
      { id: 'm5', section: 'custom', customTitle: 'Partner Expectations', label: 'Location', value: 'Mumbai / Delhi / Canada / UK' },
    ],
  },
  minimal: {
    fullName: 'Mihir Shah', dateOfBirth: '1997-06-20', age: '27', gender: 'Male',
    height: "5'9\"", weight: '68 kg', bloodGroup: 'A+',
    religion: 'Jain', caste: 'Shwetambar', subCaste: '', motherTongue: 'Gujarati',
    education: 'B.Com + Chartered Accountant', college: 'H.R. College of Commerce, Mumbai',
    occupation: 'Chartered Accountant', company: 'Deloitte India', income: '14 LPA', workLocation: 'Mumbai',
    fatherName: 'Mahesh Shah', fatherOccupation: 'Diamond Merchant',
    motherName: 'Rekha Shah', motherOccupation: 'Homemaker',
    brothers: 'None', sisters: '1 Elder Sister (Married)',
    familyType: 'Joint', familyStatus: 'Business Family', nativePlace: 'Surat, Gujarat',
    hobbies: 'Yoga, Reading, Travel, Chess', about: 'Vegetarian, ethical, spiritually inclined — believes in simplicity and right conduct',
    rashi: 'Mithuna', nakshatra: 'Punarvasu', gotra: '', manglik: 'No',
    address: '34, Walkeshwar Road', city: 'Mumbai', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'mihir.shah@email.com',
    photo: photoMinimal, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto', customFields: [],
  },
  royal: {
    fullName: 'Vikram Singh Rathore', dateOfBirth: '1996-08-14', age: '28', gender: 'Male',
    height: "5'11\"", weight: '78 kg', bloodGroup: 'B+',
    religion: 'Hindu', caste: 'Rajput', subCaste: 'Rathore', motherTongue: 'Hindi',
    education: 'MBA (Strategy)', college: 'MDI Gurgaon',
    occupation: 'Management Consultant', company: 'McKinsey & Company', income: '32 LPA', workLocation: 'New Delhi',
    fatherName: 'Col. Mahendra Singh Rathore', fatherOccupation: 'Retired Army Colonel',
    motherName: 'Meenakshi Rathore', motherOccupation: 'Homemaker',
    brothers: 'None', sisters: '1 Elder Sister (Married)',
    familyType: 'Joint', familyStatus: 'Affluent', nativePlace: 'Jodhpur, Rajasthan',
    hobbies: 'Horse Riding, Polo, Hindustani Classical Music', about: 'Proud of Rajput heritage, disciplined and strategic — honour and excellence in everything',
    rashi: 'Simha', nakshatra: 'Purva Phalguni', gotra: 'Kashyapa', manglik: 'No',
    address: '7, Friends Colony East', city: 'New Delhi', state: 'Delhi',
    phone: '+91 90000 00000', email: 'vikram.rathore@email.com',
    photo: photoRoyal, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'hindi', customFields: [],
  },
  modern: {
    fullName: 'Karthik Krishnan', dateOfBirth: '1998-04-05', age: '26', gender: 'Male',
    height: "5'9\"", weight: '67 kg', bloodGroup: 'O+',
    religion: 'Hindu', caste: 'Iyengar', subCaste: '', motherTongue: 'Tamil',
    education: 'B.Tech (AI & ML)', college: 'IIT Madras',
    occupation: 'Data Scientist', company: 'Google DeepMind India', income: '30 LPA', workLocation: 'Bengaluru',
    fatherName: 'Krishnamurthy V.', fatherOccupation: 'Retired Software Architect',
    motherName: 'Padmavathi K.', motherOccupation: 'Maths Teacher',
    brothers: 'None', sisters: '1 Younger Sister (Engineering Student)',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Chennai, Tamil Nadu',
    hobbies: 'Carnatic Violin, Machine Learning Research, Badminton', about: 'Tech-driven and culture-rooted — building AI solutions and playing Carnatic music with equal passion',
    rashi: 'Mesha', nakshatra: 'Ashwini', gotra: 'Atreya', manglik: 'No',
    address: '15, Indiranagar 12th Main', city: 'Bengaluru', state: 'Karnataka',
    phone: '+91 90000 00000', email: 'karthik.k@email.com',
    photo: photoModern, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'tamil', customFields: [],
  },
  amethyst: {
    fullName: 'Rohith Rao', dateOfBirth: '1996-09-18', age: '28', gender: 'Male',
    height: "5'10\"", weight: '72 kg', bloodGroup: 'A+',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Madhwa', motherTongue: 'Kannada',
    education: 'M.Sc (Data Science)', college: 'IISc Bengaluru',
    occupation: 'Research Scientist', company: 'Microsoft Research India', income: '22 LPA', workLocation: 'Bengaluru',
    fatherName: 'Venkatesh Rao', fatherOccupation: 'Retired Professor',
    motherName: 'Sharada Rao', motherOccupation: 'Homemaker',
    brothers: 'None', sisters: '1 Elder Sister (Married)',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Mysuru, Karnataka',
    hobbies: 'Astronomy, Trekking, Chess, Veena appreciation', about: 'Methodical and inquisitive — combines scientific rigour with deep love for classical arts',
    rashi: 'Vrishchika', nakshatra: 'Anuradha', gotra: 'Vatsa', manglik: 'No',
    address: '56, Jayanagar 4th Block', city: 'Bengaluru', state: 'Karnataka',
    phone: '+91 90000 00000', email: 'rohith.rao@email.com',
    photo: photoAmethyst, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'kannada', customFields: [],
  },
  ember: {
    fullName: 'Dhruv Desai', dateOfBirth: '1997-12-05', age: '27', gender: 'Male',
    height: "5'10\"", weight: '73 kg', bloodGroup: 'B-',
    religion: 'Hindu', caste: 'Patel', subCaste: 'Kadva', motherTongue: 'Gujarati',
    education: 'B.Pharm + MBA (Healthcare)', college: 'NMIMS Mumbai',
    occupation: 'Healthcare Consultant', company: 'McKinsey & Company', income: '28 LPA', workLocation: 'Ahmedabad',
    fatherName: 'Rajesh Desai', fatherOccupation: 'Pharmaceutical Businessman',
    motherName: 'Hiral Desai', motherOccupation: 'Interior Designer',
    brothers: 'None', sisters: '1 Elder Sister (USA)',
    familyType: 'Nuclear', familyStatus: 'Business Family', nativePlace: 'Surat, Gujarat',
    hobbies: 'Entrepreneurship, Cricket, Travel, Garba', about: 'Driven and entrepreneurial — combines sharp business instinct with cultural pride',
    rashi: 'Dhanu', nakshatra: 'Purva Ashadha', gotra: 'Kashyapa', manglik: 'No',
    address: '18, Bodakdev', city: 'Ahmedabad', state: 'Gujarat',
    phone: '+91 90000 00000', email: 'dhruv.desai@email.com',
    photo: photoEmber, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'gujarati', customFields: [],
  },
  midnight: {
    fullName: 'Kabir Bedi', dateOfBirth: '1997-07-19', age: '27', gender: 'Male',
    height: "5'11\"", weight: '75 kg', bloodGroup: 'AB+',
    religion: 'Hindu', caste: 'Khatri', subCaste: '', motherTongue: 'Punjabi',
    education: 'LL.B. + LL.M. (Corporate Law)', college: 'National Law School, Bengaluru',
    occupation: 'Corporate Lawyer', company: 'Trilegal', income: '24 LPA', workLocation: 'Mumbai',
    fatherName: 'Harish Bedi', fatherOccupation: 'Entrepreneur',
    motherName: 'Sunaina Bedi', motherOccupation: 'Oncologist',
    brothers: 'None', sisters: '1 Elder Sister (UK)',
    familyType: 'Nuclear', familyStatus: 'Affluent', nativePlace: 'Chandigarh, Punjab',
    hobbies: 'Contemporary Fiction, Cycling, Jazz Music', about: 'Sharp-minded and principled — advocates for fairness inside and outside the courtroom',
    rashi: 'Karka', nakshatra: 'Ashlesha', gotra: 'Atreya', manglik: 'No',
    address: '12, Bandra West', city: 'Mumbai', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'kabir.bedi@email.com',
    photo: photoMidnight, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'hindi', customFields: [],
  },

  // ── New Wave ─────────────────────────────────────────────────────────────
  noir: {
    fullName: 'Neel Malhotra', dateOfBirth: '1996-10-08', age: '28', gender: 'Male',
    height: "5'11\"", weight: '74 kg', bloodGroup: 'O+',
    religion: 'Hindu', caste: 'Khatri', subCaste: '', motherTongue: 'Hindi',
    education: 'B.Tech + MBA (Entrepreneurship)', college: 'IIT Delhi + ISB Hyderabad',
    occupation: 'Co-Founder & CEO', company: 'Zeno Technologies', income: '40+ LPA', workLocation: 'Mumbai',
    fatherName: 'Rajiv Malhotra', fatherOccupation: 'Industrialist',
    motherName: 'Pooja Malhotra', motherOccupation: 'Interior Designer',
    brothers: 'None', sisters: '1 Elder Sister (Married, London)',
    familyType: 'Nuclear', familyStatus: 'Affluent', nativePlace: 'New Delhi',
    hobbies: 'Venture Capital, Squash, Contemporary Art, Jazz', about: 'Founder building at the intersection of AI and consumer — looking for a partner who is as ambitious and grounded as she is',
    rashi: 'Simha', nakshatra: 'Magha', gotra: 'Kashyapa', manglik: 'No',
    address: '7, Worli Sea Face', city: 'Mumbai', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'neel.m@email.com',
    photo: photoMidnight, photoPosition: { x: 50, y: 15 }, sloganLanguage: 'hindi', customFields: [],
  },
  aurora: {
    fullName: 'Aarohi Verma', dateOfBirth: '1999-02-22', age: '25', gender: 'Female',
    height: "5'5\"", weight: '56 kg', bloodGroup: 'B+',
    religion: 'Hindu', caste: 'Brahmin', subCaste: 'Gaur', motherTongue: 'Hindi',
    education: 'B.Des (Interaction Design)', college: 'NID Ahmedabad',
    occupation: 'Senior UX Designer', company: 'Swiggy', income: '16 LPA', workLocation: 'Bengaluru',
    fatherName: 'Anil Verma', fatherOccupation: 'Architect',
    motherName: 'Smita Verma', motherOccupation: 'Kathak Dancer & Teacher',
    brothers: 'None', sisters: '1 Younger Sister (Design Student)',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Dehradun, Uttarakhand',
    hobbies: 'Astrophotography, Kathak, Illustrating, Hiking', about: 'Curious about everything — designing better experiences by day, chasing the Milky Way by night',
    rashi: 'Kumbha', nakshatra: 'Shatabhisha', gotra: 'Bharadvaja', manglik: 'No',
    address: '21, Indiranagar 100ft Road', city: 'Bengaluru', state: 'Karnataka',
    phone: '+91 90000 00000', email: 'aarohi.v@email.com',
    photo: photoCelestial, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto', customFields: [],
  },
  editorial: {
    fullName: 'Simran Dhawan', dateOfBirth: '1997-06-15', age: '27', gender: 'Female',
    height: "5'6\"", weight: '60 kg', bloodGroup: 'A+',
    religion: 'Hindu', caste: 'Arora', subCaste: '', motherTongue: 'Punjabi',
    education: 'M.A. (Mass Communication)', college: 'Jamia Millia Islamia, New Delhi',
    occupation: 'Senior Journalist', company: 'The Indian Express', income: '13 LPA', workLocation: 'New Delhi',
    fatherName: 'Harinder Dhawan', fatherOccupation: 'Businessman',
    motherName: 'Gurpreet Dhawan', motherOccupation: 'Dentist',
    brothers: '1 Younger Brother (MBA Student)', sisters: 'None',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Amritsar, Punjab',
    hobbies: 'Documentary Filmmaking, Punjabi Literature, Swimming', about: 'Opinionated, empathetic, always seeking the truth — life as a journalist taught her to listen first, write second',
    rashi: 'Mithuna', nakshatra: 'Mrigashira', gotra: 'Vasishtha', manglik: 'No',
    address: '4, Vasant Vihar', city: 'New Delhi', state: 'Delhi',
    phone: '+91 90000 00000', email: 'simran.d@email.com',
    photo: photoPeacock, photoPosition: { x: 50, y: 15 }, sloganLanguage: 'auto', customFields: [],
  },
  bloom: {
    fullName: 'Riya Singh', dateOfBirth: '1999-04-10', age: '25', gender: 'Female',
    height: "5'4\"", weight: '53 kg', bloodGroup: 'O+',
    religion: 'Hindu', caste: 'Rajput', subCaste: 'Tomar', motherTongue: 'Hindi',
    education: 'B.Des (Visual Communication)', college: 'Symbiosis Institute of Design, Pune',
    occupation: 'Graphic Designer & Illustrator', company: 'Freelance / Behance', income: '9 LPA', workLocation: 'Pune',
    fatherName: 'Surendra Singh', fatherOccupation: 'School Principal',
    motherName: 'Deepa Singh', motherOccupation: 'Yoga Instructor',
    brothers: 'None', sisters: '1 Elder Sister (Married, Jaipur)',
    familyType: 'Nuclear', familyStatus: 'Middle Class', nativePlace: 'Agra, Uttar Pradesh',
    hobbies: 'Hand Lettering, Pottery, Hiking, Plant Care', about: 'Gentle by nature, bold in creativity — finds beauty in everyday details and crafts it into art',
    rashi: 'Vrishabha', nakshatra: 'Rohini', gotra: 'Kaushika', manglik: 'No',
    address: '9, Koregaon Park Lane', city: 'Pune', state: 'Maharashtra',
    phone: '+91 90000 00000', email: 'riya.singh@email.com',
    photo: photoRose, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'auto', customFields: [],
  },
  neo: {
    fullName: 'Varun Reddy', dateOfBirth: '1997-08-26', age: '27', gender: 'Male',
    height: "5'10\"", weight: '72 kg', bloodGroup: 'B+',
    religion: 'Hindu', caste: 'Reddy', subCaste: 'Kapu', motherTongue: 'Telugu',
    education: 'B.Tech (Computer Science)', college: 'BITS Pilani',
    occupation: 'Founder & CTO', company: 'Kerno AI', income: '35+ LPA', workLocation: 'Hyderabad',
    fatherName: 'Ramprasad Reddy', fatherOccupation: 'Retired IPS Officer',
    motherName: 'Anitha Reddy', motherOccupation: 'Oncologist',
    brothers: 'None', sisters: '1 Younger Sister (CS Student, USA)',
    familyType: 'Nuclear', familyStatus: 'Upper Middle Class', nativePlace: 'Vijayawada, Andhra Pradesh',
    hobbies: 'Open Source, Powerlifting, Black-and-white Photography', about: 'Builds fast, thinks long-term — values depth over noise and is looking for someone who matches that energy',
    rashi: 'Makara', nakshatra: 'Uttara Ashadha', gotra: 'Gautama', manglik: 'No',
    address: '15, Jubilee Hills Road 36', city: 'Hyderabad', state: 'Telangana',
    phone: '+91 90000 00000', email: 'varun.reddy@email.com',
    photo: photoModern, photoPosition: { x: 50, y: 20 }, sloganLanguage: 'telugu', customFields: [],
  },
}

const PRIYA_DATA = SAMPLE_BY_TEMPLATE.lotus

export default function LivePreview({ containerW, visibleH, shadow = true, template }) {
  const naturalW = 760
  const scale = containerW / naturalW
  const innerRef = useRef(null)
  const [naturalH, setNaturalH] = useState(0)
  const base = template ? (SAMPLE_BY_TEMPLATE[template] || PRIYA_DATA) : PRIYA_DATA
  const previewData = { ...base, template: template || base.template }

  useLayoutEffect(() => {
    if (innerRef.current) setNaturalH(innerRef.current.scrollHeight)
  }, [containerW, template])

  const outerH = visibleH ?? (naturalH ? naturalH * scale : 'auto')

  return (
    <div style={{ width: containerW, height: outerH, overflow: 'hidden', flexShrink: 0,
      boxShadow: shadow ? '0 24px 60px rgba(201,160,53,0.2), 0 8px 24px rgba(0,0,0,0.3)' : 'none' }}>
      <div ref={innerRef} style={{ width: naturalW, transform: `scale(${scale})`, transformOrigin: 'top left', pointerEvents: 'none' }}>
        <BioTemplate data={previewData} />
      </div>
    </div>
  )
}
